sca

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -10,35 +10,34 @@ jobs:
   SCA:
     runs-on: 24.04
     steps: 
-
-    - name: Checkout code
-      uses: actions/checkout@v2
-    
-    - name: Dependency-Check
+  
+    - name: Dependency Check
       uses: dependency-check/Dependency-Check_Action@1.1.0
-      env: 
-        JAVA_HOME: opt/jdk
+      env:
+        JAVA_HOME: /opt/jdk
       id: Depcheck
-      with: 
-        name: dependency-check-report
-        path: dependency-check-report
+      with:
+        project: '${{ github.event.repository.name }}'
+        path: '.'
+        format: 'HTML'
         args: >
           --out ./reports
           --failOnCVSS 7
           --enableRetired
-    
-    - name: Upload Dependency-Check Report as Artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: dependency-check-report
-        path: dependency-check-report
-    
-    - name: Check Dependency-Check Report for Vulnerabilities
-      run: |
-        if grep -iq "Critical\|High\|Medium" dependency-check-report/dependency-check-report.json; then
-            echo "Vulnerabilities found! Failing the build."
-            exit 1
-        else
-          echo "No critical, high, or medium vulnerabilities found."
-          fi
 
+    - name: Upload Test Result
+      uses: actions/upload-artifact@master
+      with:
+        name: Depcheck Report
+        path: ./reports
+      
+    - name: Check for vulnerabilities
+      run: |
+        if grep -q 'CRITICAL\|HIGH\|MEDIUM' dependency-check-report/dependency-check-report.html; then
+          echo "Found vulnerabilities: Failing the build"
+          exit 1
+        else
+          echo "No critical, high, or medium vulnerabilities found"
+        fi
+  
+    
