sast

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -18,4 +18,16 @@ jobs:
         with:
           args: >
               -Dsonar.organization="laboratorio-final-devsecops"
-              -Dsonar.projectKey="Laboratorio-Final-DevSecOps_Laboratorio-N-R"   
+              -Dsonar.projectKey="Laboratorio-Final-DevSecOps_Laboratorio-N-R"    
+              
+      - name: Check Quality Gate Status
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          STATUS=$(curl -s -u $SONAR_TOKEN: \
+            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Laboratorio-Final-DevSecOps_Laboratorio-N-R" \ | jq -r '.projectStatus.status')
+          echo "Quality Gate Status: $STATUS"
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed. Vulnerabilities detected!"
+            exit 1
+          fi
