qg

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -1,42 +1,45 @@
-name: Workflow
+name: Workflow 
+
 on:
-  push: 
+  push:
     branches:
-        - main
-
+      - main
+  
 jobs:
-  SCA:
-    runs-on: ubuntu-24.04
-    steps:
-    
-    - name: Checkout code
-      uses: actions/checkout@v2
-    
-    - name: Análisis SCA con Dependency Check
-      uses: dependency-check/Dependency-Check_Action@1.1.0
-      env:
-        JAVA_HOME: /opt/jdk
-      id: Depcheck
-      with:
-        project: '${{ github.event.repository.name }}'
-        path: '.'
-        format: 'HTML'
-        args: >
-          --format JSON --out results.json
-        fail-on: HIGH,MEDIUM,LOW
-    
-    - name: Verificar vulnerabilidades
-      run: |
-        if [ -f results.json ]; then
-            vulnerabilities=$(jq '.dependencies[] | select(.vulnerability.severity == "HIGH" or .vulnerability.severity == "MEDIUM" or .vulnerability.severity == "MAJOR")' results.json)
-            if [ -n "$vulnerabilities" ]; then
-              echo "Se detectaron vulnerabilidades."
-              exit 1
-            fi
-          fi       
+  SAST:
+    runs-on: ubuntu-latest
 
-    - name: Upload Test Result
-      uses: actions/upload-artifact@master
+    steps:
+    - name: Check out the repository
+      uses: actions/checkout@v2
+#SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
+
+    - name: Set up JDK 17
+      uses: actions/setup-java@v2
       with:
-        name: Depcheck Report
-        path: ./reports
+        java-version: '17'
+        distribution: 'adopt'
+
+    - name: SonarCloud Scan
+      uses: SonarSource/sonarcloud-github-action@master
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      with:
+        args: >
+          -Dsonar.projectKey=Laboratorio-Final-DevSecOps_Laboratorio-N-R
+          -Dsonar.organization=laboratorio-final-devsecops
+          -Dsonar.host.url=https://sonarcloud.io
+          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+            
+    - name: Check SonarCloud Quality Gate
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+        STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
+        "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Laboratorio-Final-DevSecOps_Laboratorio-N-R" \
+        | jq -r '.projectStatus.status')
+        echo "SonarCloud Quality Gate Status: $STATUS"
+        if [ "$STATUS" != "OK" ]; then
+          echo "❌ SonarCloud Quality Gate failed: $STATUS"
+          exit 1
+        fi
