sast

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -23,15 +23,19 @@ jobs:
           -Dsonar.organization=laboratorio-final-devsecops
           -Dsonar.host.url=https://sonarcloud.io
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
-
-    - name: Quality Gate Check
-      run: |
-        QG_STATUS=$(curl -s -u $SONAR_TOKEN: \
-          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Laboratorio-Final-DevSecOps_Laboratorio-N-R" \
-          | jq -r '.projectStatus.status')
-        if [ "$QG_STATUS" != "OK" ]; then
-          echo "Quality Gate failed: $QG_STATUS"
-          exit 1
-        fi
+      
+    - name: Check SonarCloud Quality Gate
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
+          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Laboratorio-Final-DevSecOps_Laboratorio-N-R" \
+          | jq -r '.projectStatus.status')
+          echo "SonarCloud Quality Gate Status: $STATUS"
+          if [ "$STATUS" != "OK" ]; then
+            echo "❌ SonarCloud Quality Gate failed: $STATUS"
+            exit 1
+          fi
+
+
+
