sast

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -1,25 +1,35 @@
 name: Workflow
-
 on:
-  push:
+  push: 
     branches:
-      - main
+        - feat
 
 jobs:
   SAST:
     runs-on: ubuntu-latest
-    steps:
-      - name: Checkout código
-        uses: actions/checkout@v3
-      
-      - name: Análisis con SonarCloud 
+    steps: 
+      - uses: actions/checkout@v3
+        with: 
+            fetch-depth: 0
+      - name: SonarCloud Scan
+        uses: Sonarsource/sonarcloud-github-action@master
         env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          
+            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
+        with:
+          args: >
+              -Dsonar.organization="laboratorio-final-devsecops"
+              -Dsonar.projectKey="Laboratorio-Final-DevSecOps_Laboratorio-N-R"   
+      
+      - name: Check quality gate status
         run: |
-            -Dsonar.projectKey=$Laboratorio-Final-DevSecOps_Laboratorio-N-R \
-            -Dsonar.organization=laboratorio-final-devsecops \
-            -Dsonar.host.url=https://sonarcloud.io \
-            -Dsonar.token=$SONAR_TOKEN \
-            -Dsonar.branch.name=main
+          echo "Checking SonarCloud Quality Gate status..."
+          QUALITY_GATE_STATUS=$(curl -s -X GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=<Laboratorio-Final-DevSecOps_Laboratorio-N-R>" \
+          -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" | jq -r '.projectStatus.status')
+
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+            echo "Quality Gate failed: $QUALITY_GATE_STATUS"
+            exit 1
+          else
+            echo "Quality Gate passed: $QUALITY_GATE_STATUS"
+          fi
