sca

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -6,28 +6,35 @@ on:
       - main
   
 jobs:
+
   SCA:
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
 
     steps: 
-    
-    - name: Checkout
+    - name: Checkout code
       uses: actions/checkout@v2
-
-    - name: Depcheck
-      uses: dependency-check/Dependency-Check_Action@main
+    
+    - name: Dependency-Check
+      uses: dependency-check/Dependency-Check_Action@1.1.0
+      env: 
+        JAVA_HOME: opt/jdk
       id: Depcheck
-      with:    
-          project: 'Laboratorio-Final-DevSecOps_Laboratorio-N-R'
-          path: '.'
-          format: 'HTML'
-          out: 'reports' # this is the default, no need to specify unless you wish to override it
-          args: >
-            --failOnCVSS 7
-            --enableRetired
-
-    - name: Upload Test results
-      uses: actions/upload-artifact@master
+      with: 
+        output-directory: dependency-check-report
+        fail-build-on-vulnerability-severity: 'major,high,medium'
+    
+    - name: Upload Dependency-Check Report as Artifact
+      uses: actions/upload-artifact@v3
       with:
-        name: Depcheck report
-        path: ${{github.workspace}}/reports
+        name: dependency-check-report
+        path: dependency-check-report
+    
+    - name: Check Dependency-Check Report for Vulnerabilities
+      run: |
+        if grep -iq "Critical\|High\|Medium" dependency-check-report/dependency-check-report.json; then
+            echo "Vulnerabilities found! Failing the build."
+            exit 1
+        else
+          echo "No critical, high, or medium vulnerabilities found."
+        fi
+
