qg

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -20,41 +20,16 @@ jobs:
           args: >
               -Dsonar.organization="laboratorio-final-devsecops"
               -Dsonar.projectKey="Laboratorio-Final-DevSecOps_Laboratorio-N-R"   
-  SCA:
-    runs-on: ubuntu-24.04
-    steps:
-    
-    - name: Checkout code
-      uses: actions/checkout@v2
-    
-    - name: Dependency Check
-      uses: dependency-check/Dependency-Check_Action@1.1.0
-      env:
-        JAVA_HOME: /opt/jdk
-      id: Depcheck
-      with:
-        project: '${{ github.event.repository.name }}'
-        path: '.'
-        format: 'HTML'
-        args: >
-          --out ./reports
-          --failOnCVSS 7
-          --enableRetired
-          --format JSON --out .dependency-check-report.json
-          failOnCVSS: 0.0
+              
+      - name: Check quality gate status
+        run: |
+          echo "Checking SonarCloud Quality Gate status..."
+          QUALITY_GATE_STATUS=$(curl -s -X GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=<Laboratorio-Final-DevSecOps_Laboratorio-N-R>" \
+          -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" | jq -r '.projectStatus.status')
 
-    - name: Verificar vulnerabilidades
-      run: |
-          if [ -f .dependency-check-report.json ]; then
-            vulnerabilities=$(jq '.dependencies[] | select(.vulnerability.severity == "LOW" or .vulnerability.severity == "MEDIUM" or .vulnerability.severity == "HIGH")' .dependency-check-report.json)
-            if [ -n "$vulnerabilities" ]; then
-              echo "Se detectaron vulnerabilidades mínimas, medias y críticas."
-              exit 1
-            fi
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+            echo "Quality Gate failed: $QUALITY_GATE_STATUS"
+            exit 1
+          else
+            echo "Quality Gate passed: $QUALITY_GATE_STATUS"
           fi
-      
-    - name: Upload Test Result
-      uses: actions/upload-artifact@master
-      with:
-        name: Depcheck Report
-        path: ./reports     
